server:
  port: 0

spring:
  application:
    name: order-service
  # datasource:
  #   url: jdbc:h2:mem:demo #메모리 기반
  #   username: sa
  #   password:
  #   driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[show_sql]': false
        '[format_sql]': false
        '[default_batch_fetch_size]': 16
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: ecommerce
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus
